### ISSUE TITLE
Language selection possible?

### ISSUE THREAD

**Issue by quamt** [rigaya/Aviutl-clfilters#1]
Hello,

Is it possible to get the plugin to be able to select another language for example English?

**Comment by rigaya** [comment]
This is filter for Aviutl, and the plugin is in Japanese only.

You mean you are using English Aviutl?

**Comment by quamt** [comment]
Yes, I am using the English translated version of AviUtl.
I also use the NVENC plugin that you wrote :-)
That one could figure out most of it as it will show the command used at the bottom.

**Comment by rigaya** [comment]
OK, I see.

I think I'll make a separate binary of English translated version, as selecting (switching) language in the same binary needs to much extra work, separate binary is much easier.

**Comment by rigaya** [comment]
[clfilters 0.02](https://github.com/rigaya/Aviutl-clfilters/releases/tag/0.02) adds English build. Please download "clfilters_en_0.02.zip".

**Comment by quamt** [comment]
Thank you.
